name: Bazaar
description: A plugin revolving around item and monetary economics.
version: '${project.version}'
main: com.dudko.bazaar.Bazaar
api-version: '1.21'
author: dudko_
commands:
  bazaar:
    description: Main plugin command.
    usage: /bazaar
    permission: bazaar.admin
  removeshop:
    description: Removes a shop.
    usage: /removeshop <id>
    permission: bazaar.admin