name: Bazaar
description: A plugin revolving around item and monetary economics.
version: '${project.version}'
main: com.dudko.bazaar.Bazaar
api-version: '1.21'
author: dudko_
commands:
  bazaar:
    description: Main plugin command.
    usage: /<command>
    permission: bazaar.admin
  removemarket:
    description: Removes a shop.
    usage: /<command> <id>
    permission: bazaar.admin
  additem:
    description: Adds a market item.
    usage: /<command> <market id>
    permission: bazaar.admin
depend:
  - Vault